/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminConsoleRouteImport } from './routes/admin-console'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as CarteiraRouteImport } from './routes/carteira'
import { Route as CorridaRouteImport } from './routes/corrida'
import { Route as EliminarContaRouteImport } from './routes/eliminar-conta'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MinhasCorridasRouteImport } from './routes/minhas-corridas'
import { Route as MotoristaRouteImport } from './routes/motorista'
import { Route as MotoristaAuthRouteImport } from './routes/motorista-auth'
import { Route as MotoristasRouteImport } from './routes/motoristas'
import { Route as MotoristasRegistoRouteImport } from './routes/motoristas-registo'
import { Route as PainelMotoristaRouteImport } from './routes/painel-motorista'
import { Route as PassageiroRouteImport } from './routes/passageiro'
import { Route as PassageiroAuthRouteImport } from './routes/passageiro-auth'
import { Route as PedirRouteImport } from './routes/pedir'
import { Route as PhoneAuthRouteImport } from './routes/phone-auth'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as TermosRouteImport } from './routes/termos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConsoleRoute = AdminConsoleRouteImport.update({
  id: '/admin-console',
  path: '/admin-console',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteiraRoute = CarteiraRouteImport.update({
  id: '/carteira',
  path: '/carteira',
  getParentRoute: () => rootRouteImport,
} as any)
const CorridaRoute = CorridaRouteImport.update({
  id: '/corrida',
  path: '/corrida',
  getParentRoute: () => rootRouteImport,
} as any)
const EliminarContaRoute = EliminarContaRouteImport.update({
  id: '/eliminar-conta',
  path: '/eliminar-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhasCorridasRoute = MinhasCorridasRouteImport.update({
  id: '/minhas-corridas',
  path: '/minhas-corridas',
  getParentRoute: () => rootRouteImport,
} as any)
const MotoristaRoute = MotoristaRouteImport.update({
  id: '/motorista',
  path: '/motorista',
  getParentRoute: () => rootRouteImport,
} as any)
const MotoristaAuthRoute = MotoristaAuthRouteImport.update({
  id: '/motorista-auth',
  path: '/motorista-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MotoristasRoute = MotoristasRouteImport.update({
  id: '/motoristas',
  path: '/motoristas',
  getParentRoute: () => rootRouteImport,
} as any)
const MotoristasRegistoRoute = MotoristasRegistoRouteImport.update({
  id: '/motoristas-registo',
  path: '/motoristas-registo',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelMotoristaRoute = PainelMotoristaRouteImport.update({
  id: '/painel-motorista',
  path: '/painel-motorista',
  getParentRoute: () => rootRouteImport,
} as any)
const PassageiroRoute = PassageiroRouteImport.update({
  id: '/passageiro',
  path: '/passageiro',
  getParentRoute: () => rootRouteImport,
} as any)
const PassageiroAuthRoute = PassageiroAuthRouteImport.update({
  id: '/passageiro-auth',
  path: '/passageiro-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PedirRoute = PedirRouteImport.update({
  id: '/pedir',
  path: '/pedir',
  getParentRoute: () => rootRouteImport,
} as any)
const PhoneAuthRoute = PhoneAuthRouteImport.update({
  id: '/phone-auth',
  path: '/phone-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-console': typeof AdminConsoleRoute
  '/ajuda': typeof AjudaRoute
  '/carteira': typeof CarteiraRoute
  '/corrida': typeof CorridaRoute
  '/eliminar-conta': typeof EliminarContaRoute
  '/login': typeof LoginRoute
  '/minhas-corridas': typeof MinhasCorridasRoute
  '/motorista': typeof MotoristaRoute
  '/motorista-auth': typeof MotoristaAuthRoute
  '/motoristas': typeof MotoristasRoute
  '/motoristas-registo': typeof MotoristasRegistoRoute
  '/painel-motorista': typeof PainelMotoristaRoute
  '/passageiro': typeof PassageiroRoute
  '/passageiro-auth': typeof PassageiroAuthRoute
  '/pedir': typeof PedirRoute
  '/phone-auth': typeof PhoneAuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-console': typeof AdminConsoleRoute
  '/ajuda': typeof AjudaRoute
  '/carteira': typeof CarteiraRoute
  '/corrida': typeof CorridaRoute
  '/eliminar-conta': typeof EliminarContaRoute
  '/login': typeof LoginRoute
  '/minhas-corridas': typeof MinhasCorridasRoute
  '/motorista': typeof MotoristaRoute
  '/motorista-auth': typeof MotoristaAuthRoute
  '/motoristas': typeof MotoristasRoute
  '/motoristas-registo': typeof MotoristasRegistoRoute
  '/painel-motorista': typeof PainelMotoristaRoute
  '/passageiro': typeof PassageiroRoute
  '/passageiro-auth': typeof PassageiroAuthRoute
  '/pedir': typeof PedirRoute
  '/phone-auth': typeof PhoneAuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-console': typeof AdminConsoleRoute
  '/ajuda': typeof AjudaRoute
  '/carteira': typeof CarteiraRoute
  '/corrida': typeof CorridaRoute
  '/eliminar-conta': typeof EliminarContaRoute
  '/login': typeof LoginRoute
  '/minhas-corridas': typeof MinhasCorridasRoute
  '/motorista': typeof MotoristaRoute
  '/motorista-auth': typeof MotoristaAuthRoute
  '/motoristas': typeof MotoristasRoute
  '/motoristas-registo': typeof MotoristasRegistoRoute
  '/painel-motorista': typeof PainelMotoristaRoute
  '/passageiro': typeof PassageiroRoute
  '/passageiro-auth': typeof PassageiroAuthRoute
  '/pedir': typeof PedirRoute
  '/phone-auth': typeof PhoneAuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-console'
    | '/ajuda'
    | '/carteira'
    | '/corrida'
    | '/eliminar-conta'
    | '/login'
    | '/minhas-corridas'
    | '/motorista'
    | '/motorista-auth'
    | '/motoristas'
    | '/motoristas-registo'
    | '/painel-motorista'
    | '/passageiro'
    | '/passageiro-auth'
    | '/pedir'
    | '/phone-auth'
    | '/privacidade'
    | '/servicos'
    | '/sobre'
    | '/suporte'
    | '/termos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-console'
    | '/ajuda'
    | '/carteira'
    | '/corrida'
    | '/eliminar-conta'
    | '/login'
    | '/minhas-corridas'
    | '/motorista'
    | '/motorista-auth'
    | '/motoristas'
    | '/motoristas-registo'
    | '/painel-motorista'
    | '/passageiro'
    | '/passageiro-auth'
    | '/pedir'
    | '/phone-auth'
    | '/privacidade'
    | '/servicos'
    | '/sobre'
    | '/suporte'
    | '/termos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-console'
    | '/ajuda'
    | '/carteira'
    | '/corrida'
    | '/eliminar-conta'
    | '/login'
    | '/minhas-corridas'
    | '/motorista'
    | '/motorista-auth'
    | '/motoristas'
    | '/motoristas-registo'
    | '/painel-motorista'
    | '/passageiro'
    | '/passageiro-auth'
    | '/pedir'
    | '/phone-auth'
    | '/privacidade'
    | '/servicos'
    | '/sobre'
    | '/suporte'
    | '/termos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminConsoleRoute: typeof AdminConsoleRoute
  AjudaRoute: typeof AjudaRoute
  CarteiraRoute: typeof CarteiraRoute
  CorridaRoute: typeof CorridaRoute
  EliminarContaRoute: typeof EliminarContaRoute
  LoginRoute: typeof LoginRoute
  MinhasCorridasRoute: typeof MinhasCorridasRoute
  MotoristaRoute: typeof MotoristaRoute
  MotoristaAuthRoute: typeof MotoristaAuthRoute
  MotoristasRoute: typeof MotoristasRoute
  MotoristasRegistoRoute: typeof MotoristasRegistoRoute
  PainelMotoristaRoute: typeof PainelMotoristaRoute
  PassageiroRoute: typeof PassageiroRoute
  PassageiroAuthRoute: typeof PassageiroAuthRoute
  PedirRoute: typeof PedirRoute
  PhoneAuthRoute: typeof PhoneAuthRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ServicosRoute: typeof ServicosRoute
  SobreRoute: typeof SobreRoute
  SuporteRoute: typeof SuporteRoute
  TermosRoute: typeof TermosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-console': {
      id: '/admin-console'
      path: '/admin-console'
      fullPath: '/admin-console'
      preLoaderRoute: typeof AdminConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carteira': {
      id: '/carteira'
      path: '/carteira'
      fullPath: '/carteira'
      preLoaderRoute: typeof CarteiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corrida': {
      id: '/corrida'
      path: '/corrida'
      fullPath: '/corrida'
      preLoaderRoute: typeof CorridaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eliminar-conta': {
      id: '/eliminar-conta'
      path: '/eliminar-conta'
      fullPath: '/eliminar-conta'
      preLoaderRoute: typeof EliminarContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minhas-corridas': {
      id: '/minhas-corridas'
      path: '/minhas-corridas'
      fullPath: '/minhas-corridas'
      preLoaderRoute: typeof MinhasCorridasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motorista': {
      id: '/motorista'
      path: '/motorista'
      fullPath: '/motorista'
      preLoaderRoute: typeof MotoristaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motorista-auth': {
      id: '/motorista-auth'
      path: '/motorista-auth'
      fullPath: '/motorista-auth'
      preLoaderRoute: typeof MotoristaAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motoristas': {
      id: '/motoristas'
      path: '/motoristas'
      fullPath: '/motoristas'
      preLoaderRoute: typeof MotoristasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motoristas-registo': {
      id: '/motoristas-registo'
      path: '/motoristas-registo'
      fullPath: '/motoristas-registo'
      preLoaderRoute: typeof MotoristasRegistoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel-motorista': {
      id: '/painel-motorista'
      path: '/painel-motorista'
      fullPath: '/painel-motorista'
      preLoaderRoute: typeof PainelMotoristaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passageiro': {
      id: '/passageiro'
      path: '/passageiro'
      fullPath: '/passageiro'
      preLoaderRoute: typeof PassageiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passageiro-auth': {
      id: '/passageiro-auth'
      path: '/passageiro-auth'
      fullPath: '/passageiro-auth'
      preLoaderRoute: typeof PassageiroAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedir': {
      id: '/pedir'
      path: '/pedir'
      fullPath: '/pedir'
      preLoaderRoute: typeof PedirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phone-auth': {
      id: '/phone-auth'
      path: '/phone-auth'
      fullPath: '/phone-auth'
      preLoaderRoute: typeof PhoneAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminConsoleRoute: AdminConsoleRoute,
  AjudaRoute: AjudaRoute,
  CarteiraRoute: CarteiraRoute,
  CorridaRoute: CorridaRoute,
  EliminarContaRoute: EliminarContaRoute,
  LoginRoute: LoginRoute,
  MinhasCorridasRoute: MinhasCorridasRoute,
  MotoristaRoute: MotoristaRoute,
  MotoristaAuthRoute: MotoristaAuthRoute,
  MotoristasRoute: MotoristasRoute,
  MotoristasRegistoRoute: MotoristasRegistoRoute,
  PainelMotoristaRoute: PainelMotoristaRoute,
  PassageiroRoute: PassageiroRoute,
  PassageiroAuthRoute: PassageiroAuthRoute,
  PedirRoute: PedirRoute,
  PhoneAuthRoute: PhoneAuthRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ServicosRoute: ServicosRoute,
  SobreRoute: SobreRoute,
  SuporteRoute: SuporteRoute,
  TermosRoute: TermosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
